### ISSUE TITLE
Overriding ability for the mvn repository url to download jar from

### ISSUE THREAD

**Issue by Macadoshis** [veracode/veracode-uploadandscan-action#18]
Please make the mvn target repository overridable, particularly for GH Enterprise private instances whose most of them have their Internet access blocked or ssl access enforced by restrictive certificates, and thus benefit from their intranet nexus instance (less download time and security compliance).

https://github.com/veracode/veracode-uploadandscan-action/blob/e86714cf9d98f634d8bc2011992fc4dd74c70a7d/entrypoint.sh#L240-L244

Based on other jar-downloading tools like the [`maven-wrapper`](https://github.com/apache/maven-wrapper/blob/master/maven-wrapper/src/test/resources/org/apache/maven/wrapper/wrapper.properties), please expose the url as an overridable parameter or environment variable, and only fallback to https://repo1.maven.org/maven2 if not set.

Something like :

```yaml
- name: Veracode Upload And Scan
  uses: veracode/veracode-uploadandscan-action
  env:
    MVNW_REPOURL: "https://nexus.mycompany.com/repository/maven-central"
```

```bash
# entrypoint.sh
if [ ! -n "$MVNW_REPOURL" ]; then
MVNW_REPOURL="https://repo1.maven.apache.org/maven2"
fi

javawrapperversion=$(curl $MVNW_REPOURL/com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/maven-metadata.xml | grep latest |  cut -d '>' -f 2 | cut -d '<' -f 1)

#echo "javawrapperversion: $javawrapperversion"

curl -sS -o VeracodeJavaAPI.jar "$MVNW_REPOURL/com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/$javawrapperversion/vosp-api-wrappers-java-$javawrapperversion.jar"
```
