### ISSUE TITLE
macOS Support

### ISSUE THREAD

**Issue by NinjaLikesCheez** [veracode/veracode-uploadandscan-action#32]
Currently, this action doesn't support macOS as GitHub doesn't allow `docker` actions to run on anything but Linux VMs (see: [About custom actions](https://docs.github.com/en/actions/creating-actions/about-custom-actions#types-of-actions)).

Other than ensuring a stable java environment, there doesn't seem to be anything that forces the use of docker - this could become a JavaScript action other than a growth in complexity. 

If that's not desirable, could we document a workaround so that this can be used in a workflow that relies on macOS?

## Example Workflow

```yml
jobs:
  build:
    name: Build
    runs-on: macos-12
    
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      # SNIP: steps to build an iOS application

      - uses: actions/upload-artifact@v3
        with:
          path: path/to/iOSApplication.zip
  scan:
      name: Scan
      runs-on: ubuntu-latest
      needs: build
      steps:
        - uses: actions/download-artifact@v3
          with:
            path: iOSApplication.zip
  
        - name: Upload & Scan
          uses: veracode/veracode-uploadandscan-action@0.2.4
          with:
            appname: 'MyTestApp'
            filepath: 'iOSApplication.zip'
            vid: 'FakeID'
            vkey: 'FakeKey'
```

Related to #9
