### ISSUE TITLE
VERACODE/veracode-uploadandscan-action is not allowed to be used in xxx-workflows

### ISSUE THREAD

**Issue by prabhat-shukla-db** [veracode/veracode-uploadandscan-action#35]
Hi ,

I am getting below error, not sure if i am doing anything wrong or it's problem in this code 

**> veracode/veracode-uploadandscan-action@0.2.4 is not allowed to be used in xxx-jxxxx/xx-xxxxxx-x-xxx-workflows. Actions in this workflow must be: within a repository that belongs to your Enterprise account, created by GitHub, or matching the following: Veracode/veracode-pipeline-scan-results-to-sarif@v0.1.*, actions/, artifactory.sdlc.ctl.gcp.db.com/dkr-all/com/db/cptce/sdlc/, distributhor/workflow-webhook@6edfd7cdaf8e0551b717bab8912c8d910475b98f, github/, google-github-actions/auth@f3c3e206c94d56ae17c8fa97b102276d24dc2108, google-github-actions/get-secretmanager-secrets@v0.2.*, google-github-actions/release-please-action@fabd3458cae1e87c5875aba495c7d6e18ac6172f, google-github-actions/setup-gcloud@v0, google-github-actions/setup-gcloud@daadedc81d5f9d3c06d2c92f49202a3cc2b919ba, google-github-actions/setup-gcloud@master, googlecloudplatform/github-actions/setup-gcloud@master, hashicorp/packer-github-actions@2ef5cf325f2beace99a1742903eb52542765c08f, hashicorp/setup-terraform@v1*, peter**

**Comment by tjarrettveracode** [comment]
Hi @prabhat-shukla-db , can you clarify, are you trying to use this action on a cloud or private GitHub instance? The action seems to be working for me on projects where I have it included in workflows. 

I wonder if your organization has restrictions on which GitHub actions are allowed?

**Comment by prabhat-shukla-db** [comment]
Hi @tjarrettveracode , 

Thanks for reply, 
 I am trying to upload my scanning directory using this action. Below is my code .


```

    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Fetch Secrets
      uses: ./.github/actions/fetch-secrets
      with:
        PROJECT ${{ secrets.PROJECT }}
        CREDENTIALS: ${{ secrets.CREDENTIALS}}

    - run: zip -r veracode-scan-target.zip ./
        
    - name: Veracode Upload And Scan
      uses: veracode/veracode-uploadandscan-action@0.2.4
      with:
        appname: 'VeraDemo'
        createprofile: false
        filepath: 'veracode-scan-target.zip'
        vid: '${{ env.VERACODE_APP_ID}}'
        vkey: '${{ env.VERACODE_APP_SECRET_KEY }}'
```
